name: build

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: antoniocsjunior/easyquiz-graphql

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run ts-lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test
        env:
          DB_STORAGE: './__tests__/database.sqlite'

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./__tests__/coverage/lcov.info

      - name: Extract version from package.json
        id: gnv
        uses: martinbeentjes/npm-get-version-action@master

      - name: Extract commit hash
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: antoniocsjunior
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ steps.gnv.current-version}},${{ env.IMAGE_NAME }}:${{ steps.commit.outputs.short }}

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_NAME }}
          args: --file=Dockerfile

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
